authuser/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^login/$', views.login_user, name='login'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
]

probegin/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from probegin import views

urlpatterns = [
    url(r'^auth/', include(('authuser.urls', 'authuser'), namespace='auth')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.post_list, name='post_list'),
    url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^comment/(?P<pk_post>\d+)/$', views.add_comment, name='add_comment'),

]

probegin/models.py
from django.contrib.auth.models import User
from django.utils import timezone

from django.db import models


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.author

authuser/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class LoginForm(AuthenticationForm):
    email = forms.CharField(label="email", max_length=30,
                               widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'email'}))
    password = forms.CharField(label="Password", max_length=30,
                               widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'password'}))

    class Meta:
        model = User
        fields = ('email', 'password1')

probegin/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

authuser/views.py
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate

from authuser import user_authenticate
from probegin import settings
from .forms import SignupForm, LoginForm
from django.contrib.auth.views import LoginView
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.core.mail import EmailMessage
from django.contrib.auth import logout
from django.contrib.auth import authenticate, login


def logout_view(request):
    logout(request)
    return redirect("/")


def login_user(request):
    form = LoginForm(request.POST)
    if request.POST:
        useremail = request.POST.get('email', '')
        password = request.POST.get('password', '')
        user = user_authenticate.MyAuth.authenticate(request, email=useremail, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect("/")
            else:
                pass
        else:
            return render(request, 'login.html', {'form': form})
    else:
        form = LoginForm(request.POST)
        return render(request, 'login.html', {'form': form})


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your blog account.'
            message = render_to_string('email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            return HttpResponse('Please confirm your email address to complete the registration')
    else:
        form = SignupForm()
    return render(request, 'signup.html', {'form': form})


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return redirect('/')
    else:
        return HttpResponse('Activation link is invalid!')

probegin/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from probegin.forms import PostForm, CommentForm
from probegin.serializers import PostSerializer
from .models import Post, Comment


def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    serializer = PostSerializer(posts, many=True)
    return render(request, 'post_list.html', {'posts': serializer.data})


@login_required
def post_detail(request, pk):
    post = Post.objects.prefetch_related('comment_set').get(pk=pk)
    serializer = PostSerializer(post)
    comment = CommentForm()
    return render(request, 'post_detail.html', {'post': serializer.data, 'add_comment': comment})


def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'post_edit.html', {'form': form})


def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'post_edit.html', {'form': form})


@login_required
def add_comment(request, pk_post):
    post = get_object_or_404(Post, pk=pk_post)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm(request.POSTs)
    return render(request, 'post_edit.html', {'add_comment': form})

authuser/templates/email.html
{% autoescape off %}
    Hi {{ user.username }},
    Please click on the link to confirm your registration,
    http://{{ domain }}{% url 'auth:activate' uidb64=uid token=token %}
{% endautoescape %}

authuser/templates/login.html
{% extends "base.html" %}
{% block content %}
 <h2>Login</h2>
{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'auth:login' %}">
{% csrf_token %}

<p>
    {{ form.email.errors }}
    {{ form.email.label_tag }}
    {{ form.email }}
</p>
<p>
    {{ form.password.errors }}
    {{ form.password.label_tag }}
    {{ form.password }}
</p>


<input type="submit" value="login" />
</form>
<div class="registration">
    <span>Still not registered ?</span>
    <a href="{% url 'auth:signup'%}">register</a>
</div>



{% endblock %}

authuser/templates/signup.html
{% extends "base.html" %}
{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
      {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="display: none">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
      {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

probegin/templates/post_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% endif %}
        {% if user.is_authenticated and request.user.is_superuser%}
            <a class="btn btn-default" href="{% url 'post_edit' pk=post.id %}"><span class="glyphicon glyphicon-pencil"></span></a>
        {% endif %}
        <h1>{{ post.title }}</h1>
        <p>{{ post.text|linebreaksbr }}</p>
    </div>
    <div class="comment">
         {% if user.is_authenticated%}
            <button type="button" class="btn btn-fill btn-default btn-xs" data-toggle="modal"
                data-target="#CommentModal"><i
                class="fa fa-plus-square"></i> Add comment
            </button>
         {%else%}
        <a href="{% url 'auth:login' %}">Sign in to leave comments</a>
        {%endif%}
    </div>

    <div class="comment_list">
        {% for item in post.comment_set%}
            <div class="item_comment">
                <div class="comment__head">
                    <span class="user-info"> {{item.author}}</span>
                    <time class="comment__date-time"> {{item.created_date}}</time>
                </div>

            </div>
                {{item.text}}
        {%endfor%}
    </div>


<div class="modal fade" id="CommentModal" tabindex="-1" role="dialog" aria-labelledby="CommentModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="CommentModalLabel">Add comment</h4>
            </div>
            <form name="add_weight" action="{% url 'add_comment' pk_post=post.id%}" method="post">
                <div class="modal-body">
                    {% csrf_token %}
                {{ add_comment.text }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-success">Add</button>
                </div>
            </form>
        </div>
    </div>
</div>
<body>
{% endblock %}

probegin/templates/post_edit.html
{% extends 'base.html' %}

{% block content %}
    <h1>New post</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

probegin/templates/post_list.html
{% extends 'base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <div class="date">
                {{ post.published_date }}
            </div>
            <h1><a href="{% url 'post_detail' pk=post.id %}">{{ post.title }}</a></h1>
            <p>{{ post.text|linebreaksbr }}</p>
        </div>
    {% endfor %}
{% endblock %}

templates/base.html
{% load staticfiles %}
<html>
    <head>
        <title>PROBEGIN BLOG</title>
         <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
         <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
         <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
    </head>
<body>
    <div class="page-header">

        {% if request.user.is_authenticated and request.user.is_superuser%}
            <a href="{% url 'post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
        {% endif %}

        <h1><a href="/">PROBEGIN BLOG</a></h1>
        {% if request.user.is_authenticated %}
            <a href="{% url 'auth:logout' %}" class="logout">logout</a>
        {%endif%}
        {% if not request.user.is_authenticated %}
            <a href="{% url 'auth:login' %}" class="login">login</a>
        {%endif%}
    </div>
    <div class="content container">
        <div class="row">
            <div class="col-md-12">
            {% block content %}

            {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>